[versions]
# Shared
shared-cloud = "2.0.0-beta.10"

# Common
common-adventure-api = "4.18.0"
common-reflections = "0.10.2"
common-log4j = "2.19.0"
common-cloud = "2.0.0"
common-configlib = "4.6.1"

# Paper
paper-api = "1.19.3-R0.1-SNAPSHOT"
paper-hooker = "1.0.2"

# Dumpster
dumpster-mongo = "5.5.1"
dumpster-gson = "2.13.1"

kotlin = "2.1.20"

[libraries]
# Common
common-adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "common-adventure-api" }
common-reflections = { group = "org.reflections", name = "reflections", version.ref = "common-reflections" }
common-log4j = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "common-log4j" }
common-cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "common-cloud" }
common-configlib = { group = "de.exlll", name = "configlib-yaml", version.ref = "common-configlib" }

# Paper
paper-hooker = { group = "info.preva1l.hooker", name = "Hooker", version.ref = "paper-hooker" }
paper-cloud = { group = "org.incendo", name = "cloud-paper", version.ref = "shared-cloud" }
paper-cloud-extras = { group = "org.incendo", name = "cloud-minecraft-extras", version.ref = "shared-cloud" }

# Dumpster
dumpster-mongo = { group = "org.mongodb", name = "mongodb-driver-sync", version.ref = "dumpster-mongo" }
dumpster-gson = { group = "com.google.code.gson", name = "gson", version.ref = "dumpster-gson" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version = "9.0.0-beta12" }
grgit = { id = "org.ajoberstar.grgit", version = "5.3.0" }
trashcan = { id = "info.preva1l.trashcan", version = "1.0.3" }

[bundles]
# Common
common-provided = [ "common-log4j", "common-adventure-api" ]
common-loaded = [ "common-reflections", "common-cloud-annotations", "common-configlib" ]
common-included = [  ]

# Paper
paper-loaded = [ "paper-cloud", "paper-cloud-extras" ]
paper-included = [ "paper-hooker" ]